### ISSUE TITLE
Docker labels adding extra double quotes

### ISSUE THREAD

**Issue by DMaxfield-BDS** [StarChart-Labs/flare-publishing-plugins#38]
When leveraging the functionality to add Docker labels, it is being added with extra double quotes. The expected output of "docker inspect <image>" would include the label information as follows:

```
            "Labels": {
                "builddate": "Wed Jun 26 12:02:29 EDT 2019",
                "version": "1.0.0-SNAPSHOT"
            }
```

The current implementation of labels looks like:

```
            "Labels": {
                "\"buildtime": "Wed Sep  4 16:37:41 EDT 2019\"",
                "\"version": "4.1.0-SNAPSHOT\""
            }
```

I believe the culprit is: src/main/groovy/org/starchartlabs/flare/publishing/task/ContainerBuildTask.groovy:62

**Comment by romeara** [comment]
@Garlog7712 What version of Docker are you using? Using `Docker version 19.03.2, build 6a30dfc`, I get the following results from `docker inspect` on the test project for the plug-in:

```
 "Labels": {
    "label1": "one",
    "label2": "two"
}
```

with no extra double quotes. The DSL that produces this is

```
labels (
    "label1": "one",
    "label2": "two"
)
```

**Comment by romeara** [comment]
Fixed in associated pull request

**Comment by DMaxfield-BDS** [comment]
Local publish was not done, so validation of edits was not correct. The issue is still showing.

**Comment by romeara** [comment]
Ok, because of the observation in the PR that Windows never supported space-including labels, we can solve this with the original change request of `"${e.key}=${e.value}"`, which worked on UNix

**Comment by romeara** [comment]
Fixed in additional PR in 2.0.2
